name: Build and Test

on:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - synchronize
  push:
    branches:
      # - master
      - '*'

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies
        run: cargo fetch

      - name: Run tests
        run: cargo test

  build:
    needs: [test]
    runs-on: windows-latest
    # if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies
        run: cargo fetch

      - name: Build program
        run: cargo build --release

      - name: Create zip file
        run: |
          $outputPath = "${{ github.workspace }}/program.zip"
          Compress-Archive -Path "${{ github.workspace }}/target/*" -DestinationPath $outputPath
        shell: pwsh

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: grout-wm-artifacts
          path: |
            target
