name: Build and Test

on:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - synchronize
  push:
    branches:
      - master

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run tests and clippy
        run: |
          cargo test
          cargo clippy

  build:
    needs: [test]
    runs-on: windows-latest
    # if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build program
        run: cargo build --release

      - name: Create zip file
        run: |
          zip -r grout-wm.zip target/release

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: grout-wm
          path: grout-wm.zip
